// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Validação das variáveis de ambiente
const hasValidConfig = SUPABASE_URL && 
                       SUPABASE_PUBLISHABLE_KEY && 
                       SUPABASE_URL.startsWith('https://') &&
                       SUPABASE_URL.includes('.supabase.co') &&
                       SUPABASE_PUBLISHABLE_KEY.startsWith('eyJ') &&
                       SUPABASE_PUBLISHABLE_KEY.length > 100;

if (!hasValidConfig) {
  const errorMessage = `
╔══════════════════════════════════════════════════════════════╗
║  ⚠️  ERRO: Variáveis de ambiente do Supabase não configuradas!  ║
╚══════════════════════════════════════════════════════════════╝

🔴 Se você está vendo ERR_NAME_NOT_RESOLVED:
   → O projeto Supabase pode estar PAUSADO
   → Acesse: https://supabase.com/dashboard/project/fdpnerksqonprirohxkr
   → Se estiver pausado, clique em "Restore Project"

Para corrigir, siga estes passos:

1️⃣  Verificar/Reativar o Projeto Supabase:
   https://supabase.com/dashboard/project/fdpnerksqonprirohxkr
   - Se estiver pausado, clique em "Restore"
   - Aguarde alguns minutos para reativar

2️⃣  Obter credenciais:
   https://supabase.com/dashboard/project/fdpnerksqonprirohxkr/settings/api
   - Copie o "Project URL" (deve ser: https://fdpnerksqonprirohxkr.supabase.co)
   - Copie a chave "anon public"

3️⃣  Configurar na Vercel:
   https://vercel.com/dashboard
   - Selecione: luazul-elevate
   - Vá em: Settings > Environment Variables
   - Adicione/Atualize:
     • VITE_SUPABASE_URL = https://fdpnerksqonprirohxkr.supabase.co
     • VITE_SUPABASE_PUBLISHABLE_KEY = [cole a chave anon public]
   - Marque: ✅ Production ✅ Preview ✅ Development

4️⃣  Fazer redeploy:
   - Vá em Deployments
   - Clique nos 3 pontos (...) > Redeploy

📖 Guias completos:
   - ERR_NAME_NOT_RESOLVED: Veja ERRO-DNS-SUPABASE.md
   - Configuração rápida: Veja CONFIGURAR-VERCEL-RAPIDO.md
  `;
  console.error(errorMessage);
  
  if (typeof window !== 'undefined') {
    console.error('Status das variáveis:', {
      VITE_SUPABASE_URL: SUPABASE_URL ? `✅ ${SUPABASE_URL.substring(0, 30)}...` : '❌ Não configurada',
      VITE_SUPABASE_PUBLISHABLE_KEY: SUPABASE_PUBLISHABLE_KEY ? '✅ Configurada' : '❌ Não configurada',
      '⚠️ Se ERR_NAME_NOT_RESOLVED': 'Verifique se o projeto Supabase está ativo (não pausado)'
    });
  }
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Criar cliente Supabase
// ⚠️ IMPORTANTE: As variáveis de ambiente DEVEM estar configuradas na Vercel
// Se não estiverem configuradas, o cliente será criado com valores inválidos
// e todas as operações falharão até que as variáveis sejam configuradas
const finalUrl = hasValidConfig 
  ? SUPABASE_URL! 
  : 'https://fdpnerksqonprirohxkr.supabase.co'; // Fallback apenas para evitar erro de inicialização

const finalKey = hasValidConfig 
  ? SUPABASE_PUBLISHABLE_KEY! 
  : 'INVALID_KEY_PLEASE_CONFIGURE_ENV_VARS'; // Chave inválida para forçar configuração

export const supabase = createClient<Database>(
  finalUrl,
  finalKey,
  {
    auth: {
      storage: typeof window !== 'undefined' ? localStorage : undefined,
      persistSession: hasValidConfig,
      autoRefreshToken: hasValidConfig,
    }
  }
);